# Generated by Django 3.2.5 on 2021-07-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Price', models.FloatField()),
                ('Summary', models.CharField(max_length=700)),
                ('Book', models.ImageField(upload_to='product/%y/%m/%d')),
            ],
        ),
    ]
